name: "Floe Action"
description: "AI Writing Assistant."
author: "Floe"
inputs:
  validatePullRequest:
    description: "Validate Pull Request"
    default: false
    type: "boolean"

runs:
  using: "composite"
  env:
    FLOE_API_WORKSPACE: ${{ secrets.FLOE_API_WORKSPACE }}
    FLOE_API_SECRET: ${{ secrets.FLOE_API_SECRET }}
  steps:
    - name: "Validate Pull Request"
      # uses: floe-dev/floe/validator@v1
      uses: ./packages/action/validator
      if: ${{ inputs.validatePullRequest == 'true' }}
