name: "Floe Review"
on:
  pull_request:

jobs:
  Review:
    env:
      FLOE_API_WORKSPACE: ${{ secrets.FLOE_API_WORKSPACE }}
      FLOE_API_SECRET: ${{ secrets.FLOE_API_SECRET }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Review
        uses: Floe-dev/@floe/review-action
