name: "Floe Review"
on:
  pull_request:

jobs:
  Review:
    env:
      FLOE_API_WORKSPACE: ${{ secrets.FLOE_API_WORKSPACE }}
      FLOE_API_SECRET: ${{ secrets.FLOE_API_SECRET }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Checkout the Floe repository
      - name: Checkout Floe
        uses: actions/checkout@v4
        with:
          repository: Floe-dev/floe
          path: ./.github/actions/floe-actions

      # Run the review action
      - name: Review
        uses: ./.github/actions/floe-actions/actions/review-action
